workflows:
  android-build:
    name: Android Build
    instance_type: linux_x2
    
    scripts:
      - name: Build APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    
    artifacts:
      - app/build/outputs/apk/debug/**/*.apk
